// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTeamMember = `-- name: AddTeamMember :one
INSERT INTO team_members (team_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING team_id, user_id, role
`

type AddTeamMemberParams struct {
	TeamID int32
	UserID string
	Role   string
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, addTeamMember, arg.TeamID, arg.UserID, arg.Role)
	var i TeamMember
	err := row.Scan(&i.TeamID, &i.UserID, &i.Role)
	return i, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO aws_accounts (team_id, account_id, external_id, role_arn, verified, last_verified_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, team_id, account_id, external_id, role_arn, verified, last_verified_at, created_at
`

type CreateAccountParams struct {
	TeamID         pgtype.Int4
	AccountID      string
	ExternalID     string
	RoleArn        pgtype.Text
	Verified       pgtype.Bool
	LastVerifiedAt pgtype.Timestamp
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (AwsAccount, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.TeamID,
		arg.AccountID,
		arg.ExternalID,
		arg.RoleArn,
		arg.Verified,
		arg.LastVerifiedAt,
	)
	var i AwsAccount
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.AccountID,
		&i.ExternalID,
		&i.RoleArn,
		&i.Verified,
		&i.LastVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, slug, owner_id)
VALUES ($1, $2, $3)
RETURNING id, name, slug, owner_id, created_at
`

type CreateTeamParams struct {
	Name    string
	Slug    string
	OwnerID pgtype.Text
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.Name, arg.Slug, arg.OwnerID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, name)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    name = EXCLUDED.name
RETURNING id, email, name, created_at
`

type CreateUserParams struct {
	ID    string
	Email string
	Name  pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM aws_accounts
WHERE account_id = $1 AND team_id = $2
`

type DeleteAccountParams struct {
	AccountID string
	TeamID    pgtype.Int4
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) error {
	_, err := q.db.Exec(ctx, deleteAccount, arg.AccountID, arg.TeamID)
	return err
}

const getAccountByExternalID = `-- name: GetAccountByExternalID :one
SELECT id, team_id, account_id, external_id, role_arn, verified, last_verified_at, created_at FROM aws_accounts
WHERE external_id = $1 LIMIT 1
`

func (q *Queries) GetAccountByExternalID(ctx context.Context, externalID string) (AwsAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByExternalID, externalID)
	var i AwsAccount
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.AccountID,
		&i.ExternalID,
		&i.RoleArn,
		&i.Verified,
		&i.LastVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountsByTeamID = `-- name: GetAccountsByTeamID :many
SELECT id, team_id, account_id, external_id, role_arn, verified, last_verified_at, created_at FROM aws_accounts
WHERE team_id = $1
`

func (q *Queries) GetAccountsByTeamID(ctx context.Context, teamID pgtype.Int4) ([]AwsAccount, error) {
	rows, err := q.db.Query(ctx, getAccountsByTeamID, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AwsAccount
	for rows.Next() {
		var i AwsAccount
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.AccountID,
			&i.ExternalID,
			&i.RoleArn,
			&i.Verified,
			&i.LastVerifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamByOwnerID = `-- name: GetTeamByOwnerID :one
SELECT id, name, slug, owner_id, created_at FROM teams
WHERE owner_id = $1 LIMIT 1
`

func (q *Queries) GetTeamByOwnerID(ctx context.Context, ownerID pgtype.Text) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByOwnerID, ownerID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, created_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
