// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AwsAccount struct {
	ID             int32
	TeamID         pgtype.Int4
	AccountID      string
	ExternalID     string
	RoleArn        pgtype.Text
	Verified       pgtype.Bool
	LastVerifiedAt pgtype.Timestamp
	CreatedAt      pgtype.Timestamp
}

type ChatConversation struct {
	ID           int32
	AwsAccountID pgtype.Int4
	UserID       pgtype.Text
	Title        pgtype.Text
	CreatedAt    pgtype.Timestamp
}

type ChatMessage struct {
	ID             int32
	ConversationID pgtype.Int4
	Role           string
	Content        string
	ToolCalls      []byte
	ScanContextID  pgtype.Int4
	CreatedAt      pgtype.Timestamp
}

type Scan struct {
	ID           int32
	AwsAccountID pgtype.Int4
	Status       string
	Services     []string
	Regions      []string
	OverallScore pgtype.Int4
	StartedAt    pgtype.Timestamp
	CompletedAt  pgtype.Timestamp
	CreatedAt    pgtype.Timestamp
}

type ScanFinding struct {
	ID          int32
	ScanID      pgtype.Int4
	Service     string
	Region      string
	ResourceID  string
	ResourceArn pgtype.Text
	CheckID     string
	Status      string
	Severity    string
	Title       string
	Description string
	Compliance  []string
	CreatedAt   pgtype.Timestamp
}

type Team struct {
	ID        int32
	Name      string
	Slug      string
	OwnerID   pgtype.Text
	CreatedAt pgtype.Timestamp
}

type TeamMember struct {
	TeamID int32
	UserID string
	Role   string
}

type User struct {
	ID        string
	Email     string
	Name      pgtype.Text
	CreatedAt pgtype.Timestamp
}
