# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import summarization_pb2 as summarization__pb2


class SummarizationServiceStub(object):
    """SummarizationService handles AI-powered analysis and summarization of security findings
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SummarizeFindings = channel.unary_unary(
                '/cloudcop.summarization.v1.SummarizationService/SummarizeFindings',
                request_serializer=summarization__pb2.SummarizeFindingsRequest.SerializeToString,
                response_deserializer=summarization__pb2.SummarizeFindingsResponse.FromString,
                _registered_method=True)
        self.StreamSummarizeFindings = channel.stream_unary(
                '/cloudcop.summarization.v1.SummarizationService/StreamSummarizeFindings',
                request_serializer=summarization__pb2.Finding.SerializeToString,
                response_deserializer=summarization__pb2.SummarizeFindingsResponse.FromString,
                _registered_method=True)


class SummarizationServiceServicer(object):
    """SummarizationService handles AI-powered analysis and summarization of security findings
    """

    def SummarizeFindings(self, request, context):
        """SummarizeFindings groups and analyzes raw security findings
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSummarizeFindings(self, request_iterator, context):
        """StreamSummarizeFindings allows streaming large sets of findings
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SummarizationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SummarizeFindings': grpc.unary_unary_rpc_method_handler(
                    servicer.SummarizeFindings,
                    request_deserializer=summarization__pb2.SummarizeFindingsRequest.FromString,
                    response_serializer=summarization__pb2.SummarizeFindingsResponse.SerializeToString,
            ),
            'StreamSummarizeFindings': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamSummarizeFindings,
                    request_deserializer=summarization__pb2.Finding.FromString,
                    response_serializer=summarization__pb2.SummarizeFindingsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloudcop.summarization.v1.SummarizationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloudcop.summarization.v1.SummarizationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SummarizationService(object):
    """SummarizationService handles AI-powered analysis and summarization of security findings
    """

    @staticmethod
    def SummarizeFindings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudcop.summarization.v1.SummarizationService/SummarizeFindings',
            summarization__pb2.SummarizeFindingsRequest.SerializeToString,
            summarization__pb2.SummarizeFindingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSummarizeFindings(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/cloudcop.summarization.v1.SummarizationService/StreamSummarizeFindings',
            summarization__pb2.Finding.SerializeToString,
            summarization__pb2.SummarizeFindingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
