// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: summarization.proto

package summarization

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Severity levels for security findings
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_LOW         Severity = 1
	Severity_SEVERITY_MEDIUM      Severity = 2
	Severity_SEVERITY_HIGH        Severity = 3
	Severity_SEVERITY_CRITICAL    Severity = 4
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_LOW",
		2: "SEVERITY_MEDIUM",
		3: "SEVERITY_HIGH",
		4: "SEVERITY_CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_LOW":         1,
		"SEVERITY_MEDIUM":      2,
		"SEVERITY_HIGH":        3,
		"SEVERITY_CRITICAL":    4,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_summarization_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_summarization_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_summarization_proto_rawDescGZIP(), []int{0}
}

// FindingStatus indicates whether a check passed or failed
type FindingStatus int32

const (
	FindingStatus_FINDING_STATUS_UNSPECIFIED FindingStatus = 0
	FindingStatus_FINDING_STATUS_PASS        FindingStatus = 1
	FindingStatus_FINDING_STATUS_FAIL        FindingStatus = 2
)

// Enum value maps for FindingStatus.
var (
	FindingStatus_name = map[int32]string{
		0: "FINDING_STATUS_UNSPECIFIED",
		1: "FINDING_STATUS_PASS",
		2: "FINDING_STATUS_FAIL",
	}
	FindingStatus_value = map[string]int32{
		"FINDING_STATUS_UNSPECIFIED": 0,
		"FINDING_STATUS_PASS":        1,
		"FINDING_STATUS_FAIL":        2,
	}
)

func (x FindingStatus) Enum() *FindingStatus {
	p := new(FindingStatus)
	*p = x
	return p
}

func (x FindingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FindingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_summarization_proto_enumTypes[1].Descriptor()
}

func (FindingStatus) Type() protoreflect.EnumType {
	return &file_summarization_proto_enumTypes[1]
}

func (x FindingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FindingStatus.Descriptor instead.
func (FindingStatus) EnumDescriptor() ([]byte, []int) {
	return file_summarization_proto_rawDescGZIP(), []int{1}
}

// ActionType represents the recommended action for a finding group
type ActionType int32

const (
	ActionType_ACTION_TYPE_UNSPECIFIED ActionType = 0
	ActionType_ACTION_TYPE_SUGGEST_FIX ActionType = 1 // Generate Terraform fix snippet
	ActionType_ACTION_TYPE_ALERT       ActionType = 2 // Dashboard alert
	ActionType_ACTION_TYPE_ESCALATE    ActionType = 3 // Immediate attention required
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_TYPE_UNSPECIFIED",
		1: "ACTION_TYPE_SUGGEST_FIX",
		2: "ACTION_TYPE_ALERT",
		3: "ACTION_TYPE_ESCALATE",
	}
	ActionType_value = map[string]int32{
		"ACTION_TYPE_UNSPECIFIED": 0,
		"ACTION_TYPE_SUGGEST_FIX": 1,
		"ACTION_TYPE_ALERT":       2,
		"ACTION_TYPE_ESCALATE":    3,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_summarization_proto_enumTypes[2].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_summarization_proto_enumTypes[2]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_summarization_proto_rawDescGZIP(), []int{2}
}

// Finding represents a single security finding from a scan
type Finding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`                                             // AWS service (s3, ec2, iam, etc.)
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`                                               // AWS region
	ResourceId    string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`                     // AWS resource identifier
	CheckId       string                 `protobuf:"bytes,4,opt,name=check_id,json=checkId,proto3" json:"check_id,omitempty"`                              // Security check identifier
	Status        FindingStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=cloudcop.summarization.v1.FindingStatus" json:"status,omitempty"` // Pass or fail
	Severity      Severity               `protobuf:"varint,6,opt,name=severity,proto3,enum=cloudcop.summarization.v1.Severity" json:"severity,omitempty"`  // Severity level
	Title         string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`                                                 // Short description
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`                                     // Detailed description
	Compliance    []string               `protobuf:"bytes,9,rep,name=compliance,proto3" json:"compliance,omitempty"`                                       // Compliance frameworks (CIS, SOC2, etc.)
	TimestampUnix int64                  `protobuf:"varint,10,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`          // Unix timestamp when detected
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_summarization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_summarization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_summarization_proto_rawDescGZIP(), []int{0}
}

func (x *Finding) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Finding) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Finding) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *Finding) GetCheckId() string {
	if x != nil {
		return x.CheckId
	}
	return ""
}

func (x *Finding) GetStatus() FindingStatus {
	if x != nil {
		return x.Status
	}
	return FindingStatus_FINDING_STATUS_UNSPECIFIED
}

func (x *Finding) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Finding) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Finding) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Finding) GetCompliance() []string {
	if x != nil {
		return x.Compliance
	}
	return nil
}

func (x *Finding) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

// SummarizeFindingsRequest contains findings to be summarized
type SummarizeFindingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`          // Unique scan identifier
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // AWS account ID
	Findings      []*Finding             `protobuf:"bytes,3,rep,name=findings,proto3" json:"findings,omitempty"`                    // Raw findings to summarize
	Options       *SummarizationOptions  `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`                      // Optional configuration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeFindingsRequest) Reset() {
	*x = SummarizeFindingsRequest{}
	mi := &file_summarization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeFindingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeFindingsRequest) ProtoMessage() {}

func (x *SummarizeFindingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_summarization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeFindingsRequest.ProtoReflect.Descriptor instead.
func (*SummarizeFindingsRequest) Descriptor() ([]byte, []int) {
	return file_summarization_proto_rawDescGZIP(), []int{1}
}

func (x *SummarizeFindingsRequest) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *SummarizeFindingsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SummarizeFindingsRequest) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *SummarizeFindingsRequest) GetOptions() *SummarizationOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// SummarizationOptions configures the summarization behavior
type SummarizationOptions struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	IncludeTerraformFixes bool                   `protobuf:"varint,1,opt,name=include_terraform_fixes,json=includeTerraformFixes,proto3" json:"include_terraform_fixes,omitempty"` // Generate Terraform fix snippets
	GroupByService        bool                   `protobuf:"varint,2,opt,name=group_by_service,json=groupByService,proto3" json:"group_by_service,omitempty"`                      // Group findings by service
	GroupBySeverity       bool                   `protobuf:"varint,3,opt,name=group_by_severity,json=groupBySeverity,proto3" json:"group_by_severity,omitempty"`                   // Group findings by severity
	MaxGroups             int32                  `protobuf:"varint,4,opt,name=max_groups,json=maxGroups,proto3" json:"max_groups,omitempty"`                                       // Maximum number of groups to return
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SummarizationOptions) Reset() {
	*x = SummarizationOptions{}
	mi := &file_summarization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizationOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizationOptions) ProtoMessage() {}

func (x *SummarizationOptions) ProtoReflect() protoreflect.Message {
	mi := &file_summarization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizationOptions.ProtoReflect.Descriptor instead.
func (*SummarizationOptions) Descriptor() ([]byte, []int) {
	return file_summarization_proto_rawDescGZIP(), []int{2}
}

func (x *SummarizationOptions) GetIncludeTerraformFixes() bool {
	if x != nil {
		return x.IncludeTerraformFixes
	}
	return false
}

func (x *SummarizationOptions) GetGroupByService() bool {
	if x != nil {
		return x.GroupByService
	}
	return false
}

func (x *SummarizationOptions) GetGroupBySeverity() bool {
	if x != nil {
		return x.GroupBySeverity
	}
	return false
}

func (x *SummarizationOptions) GetMaxGroups() int32 {
	if x != nil {
		return x.MaxGroups
	}
	return 0
}

// SummarizeFindingsResponse contains the summarized analysis
type SummarizeFindingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Groups        []*FindingGroup        `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`                              // Grouped findings
	RiskSummary   *RiskSummary           `protobuf:"bytes,3,opt,name=risk_summary,json=riskSummary,proto3" json:"risk_summary,omitempty"` // Overall risk assessment
	ActionItems   []*ActionItem          `protobuf:"bytes,4,rep,name=action_items,json=actionItems,proto3" json:"action_items,omitempty"` // Recommended actions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeFindingsResponse) Reset() {
	*x = SummarizeFindingsResponse{}
	mi := &file_summarization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeFindingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeFindingsResponse) ProtoMessage() {}

func (x *SummarizeFindingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_summarization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeFindingsResponse.ProtoReflect.Descriptor instead.
func (*SummarizeFindingsResponse) Descriptor() ([]byte, []int) {
	return file_summarization_proto_rawDescGZIP(), []int{3}
}

func (x *SummarizeFindingsResponse) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *SummarizeFindingsResponse) GetGroups() []*FindingGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *SummarizeFindingsResponse) GetRiskSummary() *RiskSummary {
	if x != nil {
		return x.RiskSummary
	}
	return nil
}

func (x *SummarizeFindingsResponse) GetActionItems() []*ActionItem {
	if x != nil {
		return x.ActionItems
	}
	return nil
}

// FindingGroup represents a group of similar findings
type FindingGroup struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GroupId           string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Title             string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                                // e.g., "15 S3 buckets lack encryption"
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                                    // Detailed explanation
	Severity          Severity               `protobuf:"varint,4,opt,name=severity,proto3,enum=cloudcop.summarization.v1.Severity" json:"severity,omitempty"` // Highest severity in group
	FindingCount      int32                  `protobuf:"varint,5,opt,name=finding_count,json=findingCount,proto3" json:"finding_count,omitempty"`             // Number of findings in group
	ResourceIds       []string               `protobuf:"bytes,6,rep,name=resource_ids,json=resourceIds,proto3" json:"resource_ids,omitempty"`                 // Affected resources
	CheckId           string                 `protobuf:"bytes,7,opt,name=check_id,json=checkId,proto3" json:"check_id,omitempty"`                             // Common check ID
	Service           string                 `protobuf:"bytes,8,opt,name=service,proto3" json:"service,omitempty"`                                            // AWS service
	Compliance        []string               `protobuf:"bytes,9,rep,name=compliance,proto3" json:"compliance,omitempty"`                                      // Applicable compliance frameworks
	RiskScore         int32                  `protobuf:"varint,10,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`                     // Calculated risk score (0-100)
	RecommendedAction ActionType             `protobuf:"varint,11,opt,name=recommended_action,json=recommendedAction,proto3,enum=cloudcop.summarization.v1.ActionType" json:"recommended_action,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FindingGroup) Reset() {
	*x = FindingGroup{}
	mi := &file_summarization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindingGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindingGroup) ProtoMessage() {}

func (x *FindingGroup) ProtoReflect() protoreflect.Message {
	mi := &file_summarization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindingGroup.ProtoReflect.Descriptor instead.
func (*FindingGroup) Descriptor() ([]byte, []int) {
	return file_summarization_proto_rawDescGZIP(), []int{4}
}

func (x *FindingGroup) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *FindingGroup) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FindingGroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FindingGroup) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *FindingGroup) GetFindingCount() int32 {
	if x != nil {
		return x.FindingCount
	}
	return 0
}

func (x *FindingGroup) GetResourceIds() []string {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

func (x *FindingGroup) GetCheckId() string {
	if x != nil {
		return x.CheckId
	}
	return ""
}

func (x *FindingGroup) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *FindingGroup) GetCompliance() []string {
	if x != nil {
		return x.Compliance
	}
	return nil
}

func (x *FindingGroup) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *FindingGroup) GetRecommendedAction() ActionType {
	if x != nil {
		return x.RecommendedAction
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

// RiskSummary provides overall risk metrics
type RiskSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OverallScore  int32                  `protobuf:"varint,1,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`    // Overall risk score (0-100)
	CriticalCount int32                  `protobuf:"varint,2,opt,name=critical_count,json=criticalCount,proto3" json:"critical_count,omitempty"` // Number of critical findings
	HighCount     int32                  `protobuf:"varint,3,opt,name=high_count,json=highCount,proto3" json:"high_count,omitempty"`             // Number of high findings
	MediumCount   int32                  `protobuf:"varint,4,opt,name=medium_count,json=mediumCount,proto3" json:"medium_count,omitempty"`       // Number of medium findings
	LowCount      int32                  `protobuf:"varint,5,opt,name=low_count,json=lowCount,proto3" json:"low_count,omitempty"`                // Number of low findings
	PassedCount   int32                  `protobuf:"varint,6,opt,name=passed_count,json=passedCount,proto3" json:"passed_count,omitempty"`       // Number of passed checks
	RiskLevel     string                 `protobuf:"bytes,7,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`              // "LOW", "MEDIUM", "HIGH", "CRITICAL"
	SummaryText   string                 `protobuf:"bytes,8,opt,name=summary_text,json=summaryText,proto3" json:"summary_text,omitempty"`        // AI-generated summary text
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskSummary) Reset() {
	*x = RiskSummary{}
	mi := &file_summarization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskSummary) ProtoMessage() {}

func (x *RiskSummary) ProtoReflect() protoreflect.Message {
	mi := &file_summarization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskSummary.ProtoReflect.Descriptor instead.
func (*RiskSummary) Descriptor() ([]byte, []int) {
	return file_summarization_proto_rawDescGZIP(), []int{5}
}

func (x *RiskSummary) GetOverallScore() int32 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

func (x *RiskSummary) GetCriticalCount() int32 {
	if x != nil {
		return x.CriticalCount
	}
	return 0
}

func (x *RiskSummary) GetHighCount() int32 {
	if x != nil {
		return x.HighCount
	}
	return 0
}

func (x *RiskSummary) GetMediumCount() int32 {
	if x != nil {
		return x.MediumCount
	}
	return 0
}

func (x *RiskSummary) GetLowCount() int32 {
	if x != nil {
		return x.LowCount
	}
	return 0
}

func (x *RiskSummary) GetPassedCount() int32 {
	if x != nil {
		return x.PassedCount
	}
	return 0
}

func (x *RiskSummary) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *RiskSummary) GetSummaryText() string {
	if x != nil {
		return x.SummaryText
	}
	return ""
}

// ActionItem represents a recommended action
type ActionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionId      string                 `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	ActionType    ActionType             `protobuf:"varint,2,opt,name=action_type,json=actionType,proto3,enum=cloudcop.summarization.v1.ActionType" json:"action_type,omitempty"`
	Severity      Severity               `protobuf:"varint,3,opt,name=severity,proto3,enum=cloudcop.summarization.v1.Severity" json:"severity,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	GroupId       string                 `protobuf:"bytes,6,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`                // Reference to finding group
	TerraformFix  *TerraformFix          `protobuf:"bytes,7,opt,name=terraform_fix,json=terraformFix,proto3" json:"terraform_fix,omitempty"` // Optional Terraform fix
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionItem) Reset() {
	*x = ActionItem{}
	mi := &file_summarization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionItem) ProtoMessage() {}

func (x *ActionItem) ProtoReflect() protoreflect.Message {
	mi := &file_summarization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionItem.ProtoReflect.Descriptor instead.
func (*ActionItem) Descriptor() ([]byte, []int) {
	return file_summarization_proto_rawDescGZIP(), []int{6}
}

func (x *ActionItem) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ActionItem) GetActionType() ActionType {
	if x != nil {
		return x.ActionType
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (x *ActionItem) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *ActionItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ActionItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActionItem) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ActionItem) GetTerraformFix() *TerraformFix {
	if x != nil {
		return x.TerraformFix
	}
	return nil
}

// TerraformFix contains generated Terraform code
type TerraformFix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // e.g., "aws_s3_bucket_public_access_block"
	ResourceName  string                 `protobuf:"bytes,2,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"` // e.g., "prod_logs"
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`                                     // The Terraform HCL code
	Explanation   string                 `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`                       // Why this fix is recommended
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerraformFix) Reset() {
	*x = TerraformFix{}
	mi := &file_summarization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerraformFix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerraformFix) ProtoMessage() {}

func (x *TerraformFix) ProtoReflect() protoreflect.Message {
	mi := &file_summarization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerraformFix.ProtoReflect.Descriptor instead.
func (*TerraformFix) Descriptor() ([]byte, []int) {
	return file_summarization_proto_rawDescGZIP(), []int{7}
}

func (x *TerraformFix) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *TerraformFix) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *TerraformFix) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TerraformFix) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

var File_summarization_proto protoreflect.FileDescriptor

const file_summarization_proto_rawDesc = "" +
	"\n" +
	"\x13summarization.proto\x12\x19cloudcop.summarization.v1\"\xf9\x02\n" +
	"\aFinding\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\x12\x19\n" +
	"\bcheck_id\x18\x04 \x01(\tR\acheckId\x12@\n" +
	"\x06status\x18\x05 \x01(\x0e2(.cloudcop.summarization.v1.FindingStatusR\x06status\x12?\n" +
	"\bseverity\x18\x06 \x01(\x0e2#.cloudcop.summarization.v1.SeverityR\bseverity\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"compliance\x18\t \x03(\tR\n" +
	"compliance\x12%\n" +
	"\x0etimestamp_unix\x18\n" +
	" \x01(\x03R\rtimestampUnix\"\xdd\x01\n" +
	"\x18SummarizeFindingsRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12>\n" +
	"\bfindings\x18\x03 \x03(\v2\".cloudcop.summarization.v1.FindingR\bfindings\x12I\n" +
	"\aoptions\x18\x04 \x01(\v2/.cloudcop.summarization.v1.SummarizationOptionsR\aoptions\"\xc3\x01\n" +
	"\x14SummarizationOptions\x126\n" +
	"\x17include_terraform_fixes\x18\x01 \x01(\bR\x15includeTerraformFixes\x12(\n" +
	"\x10group_by_service\x18\x02 \x01(\bR\x0egroupByService\x12*\n" +
	"\x11group_by_severity\x18\x03 \x01(\bR\x0fgroupBySeverity\x12\x1d\n" +
	"\n" +
	"max_groups\x18\x04 \x01(\x05R\tmaxGroups\"\x8a\x02\n" +
	"\x19SummarizeFindingsResponse\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12?\n" +
	"\x06groups\x18\x02 \x03(\v2'.cloudcop.summarization.v1.FindingGroupR\x06groups\x12I\n" +
	"\frisk_summary\x18\x03 \x01(\v2&.cloudcop.summarization.v1.RiskSummaryR\vriskSummary\x12H\n" +
	"\faction_items\x18\x04 \x03(\v2%.cloudcop.summarization.v1.ActionItemR\vactionItems\"\xb4\x03\n" +
	"\fFindingGroup\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12?\n" +
	"\bseverity\x18\x04 \x01(\x0e2#.cloudcop.summarization.v1.SeverityR\bseverity\x12#\n" +
	"\rfinding_count\x18\x05 \x01(\x05R\ffindingCount\x12!\n" +
	"\fresource_ids\x18\x06 \x03(\tR\vresourceIds\x12\x19\n" +
	"\bcheck_id\x18\a \x01(\tR\acheckId\x12\x18\n" +
	"\aservice\x18\b \x01(\tR\aservice\x12\x1e\n" +
	"\n" +
	"compliance\x18\t \x03(\tR\n" +
	"compliance\x12\x1d\n" +
	"\n" +
	"risk_score\x18\n" +
	" \x01(\x05R\triskScore\x12T\n" +
	"\x12recommended_action\x18\v \x01(\x0e2%.cloudcop.summarization.v1.ActionTypeR\x11recommendedAction\"\x9d\x02\n" +
	"\vRiskSummary\x12#\n" +
	"\roverall_score\x18\x01 \x01(\x05R\foverallScore\x12%\n" +
	"\x0ecritical_count\x18\x02 \x01(\x05R\rcriticalCount\x12\x1d\n" +
	"\n" +
	"high_count\x18\x03 \x01(\x05R\thighCount\x12!\n" +
	"\fmedium_count\x18\x04 \x01(\x05R\vmediumCount\x12\x1b\n" +
	"\tlow_count\x18\x05 \x01(\x05R\blowCount\x12!\n" +
	"\fpassed_count\x18\x06 \x01(\x05R\vpassedCount\x12\x1d\n" +
	"\n" +
	"risk_level\x18\a \x01(\tR\triskLevel\x12!\n" +
	"\fsummary_text\x18\b \x01(\tR\vsummaryText\"\xd3\x02\n" +
	"\n" +
	"ActionItem\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x12F\n" +
	"\vaction_type\x18\x02 \x01(\x0e2%.cloudcop.summarization.v1.ActionTypeR\n" +
	"actionType\x12?\n" +
	"\bseverity\x18\x03 \x01(\x0e2#.cloudcop.summarization.v1.SeverityR\bseverity\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x19\n" +
	"\bgroup_id\x18\x06 \x01(\tR\agroupId\x12L\n" +
	"\rterraform_fix\x18\a \x01(\v2'.cloudcop.summarization.v1.TerraformFixR\fterraformFix\"\x8e\x01\n" +
	"\fTerraformFix\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12#\n" +
	"\rresource_name\x18\x02 \x01(\tR\fresourceName\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vexplanation\x18\x04 \x01(\tR\vexplanation*u\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSEVERITY_LOW\x10\x01\x12\x13\n" +
	"\x0fSEVERITY_MEDIUM\x10\x02\x12\x11\n" +
	"\rSEVERITY_HIGH\x10\x03\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x04*a\n" +
	"\rFindingStatus\x12\x1e\n" +
	"\x1aFINDING_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13FINDING_STATUS_PASS\x10\x01\x12\x17\n" +
	"\x13FINDING_STATUS_FAIL\x10\x02*w\n" +
	"\n" +
	"ActionType\x12\x1b\n" +
	"\x17ACTION_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ACTION_TYPE_SUGGEST_FIX\x10\x01\x12\x15\n" +
	"\x11ACTION_TYPE_ALERT\x10\x02\x12\x18\n" +
	"\x14ACTION_TYPE_ESCALATE\x10\x032\x8d\x02\n" +
	"\x14SummarizationService\x12~\n" +
	"\x11SummarizeFindings\x123.cloudcop.summarization.v1.SummarizeFindingsRequest\x1a4.cloudcop.summarization.v1.SummarizeFindingsResponse\x12u\n" +
	"\x17StreamSummarizeFindings\x12\".cloudcop.summarization.v1.Finding\x1a4.cloudcop.summarization.v1.SummarizeFindingsResponse(\x01B*Z(cloudcop/api/internal/grpc/summarizationb\x06proto3"

var (
	file_summarization_proto_rawDescOnce sync.Once
	file_summarization_proto_rawDescData []byte
)

func file_summarization_proto_rawDescGZIP() []byte {
	file_summarization_proto_rawDescOnce.Do(func() {
		file_summarization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_summarization_proto_rawDesc), len(file_summarization_proto_rawDesc)))
	})
	return file_summarization_proto_rawDescData
}

var file_summarization_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_summarization_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_summarization_proto_goTypes = []any{
	(Severity)(0),                     // 0: cloudcop.summarization.v1.Severity
	(FindingStatus)(0),                // 1: cloudcop.summarization.v1.FindingStatus
	(ActionType)(0),                   // 2: cloudcop.summarization.v1.ActionType
	(*Finding)(nil),                   // 3: cloudcop.summarization.v1.Finding
	(*SummarizeFindingsRequest)(nil),  // 4: cloudcop.summarization.v1.SummarizeFindingsRequest
	(*SummarizationOptions)(nil),      // 5: cloudcop.summarization.v1.SummarizationOptions
	(*SummarizeFindingsResponse)(nil), // 6: cloudcop.summarization.v1.SummarizeFindingsResponse
	(*FindingGroup)(nil),              // 7: cloudcop.summarization.v1.FindingGroup
	(*RiskSummary)(nil),               // 8: cloudcop.summarization.v1.RiskSummary
	(*ActionItem)(nil),                // 9: cloudcop.summarization.v1.ActionItem
	(*TerraformFix)(nil),              // 10: cloudcop.summarization.v1.TerraformFix
}
var file_summarization_proto_depIdxs = []int32{
	1,  // 0: cloudcop.summarization.v1.Finding.status:type_name -> cloudcop.summarization.v1.FindingStatus
	0,  // 1: cloudcop.summarization.v1.Finding.severity:type_name -> cloudcop.summarization.v1.Severity
	3,  // 2: cloudcop.summarization.v1.SummarizeFindingsRequest.findings:type_name -> cloudcop.summarization.v1.Finding
	5,  // 3: cloudcop.summarization.v1.SummarizeFindingsRequest.options:type_name -> cloudcop.summarization.v1.SummarizationOptions
	7,  // 4: cloudcop.summarization.v1.SummarizeFindingsResponse.groups:type_name -> cloudcop.summarization.v1.FindingGroup
	8,  // 5: cloudcop.summarization.v1.SummarizeFindingsResponse.risk_summary:type_name -> cloudcop.summarization.v1.RiskSummary
	9,  // 6: cloudcop.summarization.v1.SummarizeFindingsResponse.action_items:type_name -> cloudcop.summarization.v1.ActionItem
	0,  // 7: cloudcop.summarization.v1.FindingGroup.severity:type_name -> cloudcop.summarization.v1.Severity
	2,  // 8: cloudcop.summarization.v1.FindingGroup.recommended_action:type_name -> cloudcop.summarization.v1.ActionType
	2,  // 9: cloudcop.summarization.v1.ActionItem.action_type:type_name -> cloudcop.summarization.v1.ActionType
	0,  // 10: cloudcop.summarization.v1.ActionItem.severity:type_name -> cloudcop.summarization.v1.Severity
	10, // 11: cloudcop.summarization.v1.ActionItem.terraform_fix:type_name -> cloudcop.summarization.v1.TerraformFix
	4,  // 12: cloudcop.summarization.v1.SummarizationService.SummarizeFindings:input_type -> cloudcop.summarization.v1.SummarizeFindingsRequest
	3,  // 13: cloudcop.summarization.v1.SummarizationService.StreamSummarizeFindings:input_type -> cloudcop.summarization.v1.Finding
	6,  // 14: cloudcop.summarization.v1.SummarizationService.SummarizeFindings:output_type -> cloudcop.summarization.v1.SummarizeFindingsResponse
	6,  // 15: cloudcop.summarization.v1.SummarizationService.StreamSummarizeFindings:output_type -> cloudcop.summarization.v1.SummarizeFindingsResponse
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_summarization_proto_init() }
func file_summarization_proto_init() {
	if File_summarization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_summarization_proto_rawDesc), len(file_summarization_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_summarization_proto_goTypes,
		DependencyIndexes: file_summarization_proto_depIdxs,
		EnumInfos:         file_summarization_proto_enumTypes,
		MessageInfos:      file_summarization_proto_msgTypes,
	}.Build()
	File_summarization_proto = out.File
	file_summarization_proto_goTypes = nil
	file_summarization_proto_depIdxs = nil
}
