// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: summarization.proto

package summarization

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SummarizationService_SummarizeFindings_FullMethodName       = "/cloudcop.summarization.v1.SummarizationService/SummarizeFindings"
	SummarizationService_StreamSummarizeFindings_FullMethodName = "/cloudcop.summarization.v1.SummarizationService/StreamSummarizeFindings"
)

// SummarizationServiceClient is the client API for SummarizationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SummarizationService handles AI-powered analysis and summarization of security findings
type SummarizationServiceClient interface {
	// SummarizeFindings groups and analyzes raw security findings
	SummarizeFindings(ctx context.Context, in *SummarizeFindingsRequest, opts ...grpc.CallOption) (*SummarizeFindingsResponse, error)
	// StreamSummarizeFindings allows streaming large sets of findings
	StreamSummarizeFindings(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Finding, SummarizeFindingsResponse], error)
}

type summarizationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSummarizationServiceClient(cc grpc.ClientConnInterface) SummarizationServiceClient {
	return &summarizationServiceClient{cc}
}

func (c *summarizationServiceClient) SummarizeFindings(ctx context.Context, in *SummarizeFindingsRequest, opts ...grpc.CallOption) (*SummarizeFindingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummarizeFindingsResponse)
	err := c.cc.Invoke(ctx, SummarizationService_SummarizeFindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *summarizationServiceClient) StreamSummarizeFindings(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Finding, SummarizeFindingsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SummarizationService_ServiceDesc.Streams[0], SummarizationService_StreamSummarizeFindings_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Finding, SummarizeFindingsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SummarizationService_StreamSummarizeFindingsClient = grpc.ClientStreamingClient[Finding, SummarizeFindingsResponse]

// SummarizationServiceServer is the server API for SummarizationService service.
// All implementations must embed UnimplementedSummarizationServiceServer
// for forward compatibility.
//
// SummarizationService handles AI-powered analysis and summarization of security findings
type SummarizationServiceServer interface {
	// SummarizeFindings groups and analyzes raw security findings
	SummarizeFindings(context.Context, *SummarizeFindingsRequest) (*SummarizeFindingsResponse, error)
	// StreamSummarizeFindings allows streaming large sets of findings
	StreamSummarizeFindings(grpc.ClientStreamingServer[Finding, SummarizeFindingsResponse]) error
	mustEmbedUnimplementedSummarizationServiceServer()
}

// UnimplementedSummarizationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSummarizationServiceServer struct{}

func (UnimplementedSummarizationServiceServer) SummarizeFindings(context.Context, *SummarizeFindingsRequest) (*SummarizeFindingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SummarizeFindings not implemented")
}
func (UnimplementedSummarizationServiceServer) StreamSummarizeFindings(grpc.ClientStreamingServer[Finding, SummarizeFindingsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamSummarizeFindings not implemented")
}
func (UnimplementedSummarizationServiceServer) mustEmbedUnimplementedSummarizationServiceServer() {}
func (UnimplementedSummarizationServiceServer) testEmbeddedByValue()                              {}

// UnsafeSummarizationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SummarizationServiceServer will
// result in compilation errors.
type UnsafeSummarizationServiceServer interface {
	mustEmbedUnimplementedSummarizationServiceServer()
}

func RegisterSummarizationServiceServer(s grpc.ServiceRegistrar, srv SummarizationServiceServer) {
	// If the following call panics, it indicates UnimplementedSummarizationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SummarizationService_ServiceDesc, srv)
}

func _SummarizationService_SummarizeFindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummarizeFindingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummarizationServiceServer).SummarizeFindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SummarizationService_SummarizeFindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummarizationServiceServer).SummarizeFindings(ctx, req.(*SummarizeFindingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SummarizationService_StreamSummarizeFindings_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SummarizationServiceServer).StreamSummarizeFindings(&grpc.GenericServerStream[Finding, SummarizeFindingsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SummarizationService_StreamSummarizeFindingsServer = grpc.ClientStreamingServer[Finding, SummarizeFindingsResponse]

// SummarizationService_ServiceDesc is the grpc.ServiceDesc for SummarizationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SummarizationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloudcop.summarization.v1.SummarizationService",
	HandlerType: (*SummarizationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SummarizeFindings",
			Handler:    _SummarizationService_SummarizeFindings_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSummarizeFindings",
			Handler:       _SummarizationService_StreamSummarizeFindings_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "summarization.proto",
}
