// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"cloudcop/api/internal/database"
)

type AWSAccount struct {
	ID             string          `json:"id"`
	AccountID      string          `json:"accountId"`
	ExternalID     string          `json:"externalId"`
	Verified       bool            `json:"verified"`
	RoleArn        *string         `json:"roleArn,omitempty"`
	LastVerifiedAt *string         `json:"lastVerifiedAt,omitempty"`
	Scans          []database.Scan `json:"scans,omitempty"`
}

type ActionItemSummary struct {
	ActionID    string   `json:"actionId"`
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Severity    string   `json:"severity"`
	Commands    []string `json:"commands"`
	GroupID     string   `json:"groupId"`
}

type Finding struct {
	ID          string   `json:"id"`
	Service     string   `json:"service"`
	Region      string   `json:"region"`
	ResourceID  string   `json:"resourceId"`
	CheckID     string   `json:"checkId"`
	Severity    string   `json:"severity"`
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Compliance  []string `json:"compliance,omitempty"`
}

type FindingGroupSummary struct {
	GroupID      string   `json:"groupId"`
	Title        string   `json:"title"`
	Service      string   `json:"service"`
	CheckID      string   `json:"checkId"`
	Severity     string   `json:"severity"`
	FindingCount int      `json:"findingCount"`
	ResourceIds  []string `json:"resourceIds"`
	Summary      string   `json:"summary"`
	Remedy       string   `json:"remedy"`
}

type Mutation struct {
}

type Query struct {
}

type ScanSummary struct {
	RiskLevel   string                `json:"riskLevel"`
	RiskScore   int                   `json:"riskScore"`
	SummaryText string                `json:"summaryText"`
	Groups      []FindingGroupSummary `json:"groups"`
	Actions     []ActionItemSummary   `json:"actions"`
}
