// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"cloudcop/api/internal/database"
)

type AWSAccount struct {
	ID             string          `json:"id"`
	AccountID      string          `json:"accountId"`
	ExternalID     string          `json:"externalId"`
	Verified       bool            `json:"verified"`
	RoleArn        *string         `json:"roleArn,omitempty"`
	LastVerifiedAt *string         `json:"lastVerifiedAt,omitempty"`
	Scans          []database.Scan `json:"scans,omitempty"`
}

type Finding struct {
	ID          string   `json:"id"`
	Service     string   `json:"service"`
	Region      string   `json:"region"`
	ResourceID  string   `json:"resourceId"`
	CheckID     string   `json:"checkId"`
	Severity    string   `json:"severity"`
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Compliance  []string `json:"compliance,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
